_BASE_: "Base-OneNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  BACKBONE:
      NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  OneNet:
    NUM_CLASSES: 1
    HEAD: "FCOS"
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
DATASETS:
  TRAIN: ("CrowdHuman_train",)
  TEST:  ("CrowdHuman_val",)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (37500,) # 15000 / 16 = 937.5
  MAX_ITER: 46875
  CHECKPOINT_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864, 896)
  MAX_SIZE_TRAIN: 1400
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1400
  CROP:
    ENABLED: False
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 500
OUTPUT_DIR: 'output_onenet_r50fcos_crowdhuman'
